language: node_js
node_js:
 - "node"
env:
  global:
    - MONGO_URI=mongodb://127.0.0.1/todo
    - SECRET=thisismyappsecret
    - DEBUG=true
    - TEST=true
    - DB_TYPE=MONGO
services: mongodb
before_script:
- tsc